#!/usr/bin/env python3
"""Generate LaTeX tables for the LLM extension section."""
from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Iterable

import pandas as pd


MEDIUM_LABELS = {
    "static_beacon": "Static beacon",
    "entropy_targeted": "Entropy targeted",
    "bottleneck_avoidance": "Bottleneck avoidance",
    "llm_template_safety": "Template safety",
    "llm_openai_state_only": "OpenAI state-only",
    "llm_openai_safety_strict": "OpenAI safety-strict",
    "llm_openai_entropy_lenient": "OpenAI entropy-lenient",
    "llm_replay_safety_strict": "Replay safety-strict",
}

TARGET_LABELS = {
    "llm_target_bottleneck": "Bottleneck",
    "llm_target_entropy": "Entropy",
    "llm_target_density": "Density",
    "llm_target_static": "Static",
    "llm_target_global": "Global",
    "llm_target_exposure": "Exposure",
}

MEDIUM_ORDER = list(MEDIUM_LABELS)
TARGET_ORDER = list(TARGET_LABELS)
HAZARD_ORDER = ["low", "medium", "high"]
HAZARD_LABELS = {"low": "Low", "medium": "Medium", "high": "High"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--medium",
        default="../out/llm_medium/tables/llm_policy_comparison.csv",
        help="Medium LLM policy comparison CSV.",
    )
    parser.add_argument(
        "--target",
        default="../out/llm_target_selection_ablation/tables/llm_policy_comparison.csv",
        help="Target-selection LLM policy comparison CSV.",
    )
    parser.add_argument(
        "--llm-regime",
        default="../out/llm_regime_robustness/tables/llm_policy_comparison.csv",
        help="LLM regime robustness policy comparison CSV.",
    )
    parser.add_argument(
        "--det-regime",
        default="../out/regime_robustness_900/tables/regime_summary.csv",
        help="Deterministic regime robustness summary CSV.",
    )
    parser.add_argument("-o", "--output", default="llm_tables.tex")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    medium = pd.read_csv(args.medium)
    target = pd.read_csv(args.target)
    llm_regime = pd.read_csv(args.llm_regime)
    det_regime = pd.read_csv(args.det_regime)

    output = "\n\n".join(
        [
            "% Auto-generated by paper/scripts/gen_llm_tables.py -- do not edit.",
            _medium_table(medium),
            _target_table(target),
            _llm_regime_table(llm_regime),
            _regime_comparison_table(det_regime, llm_regime),
        ]
    )
    Path(args.output).write_text(output + "\n", encoding="utf-8")
    return 0


def _medium_table(frame: pd.DataFrame) -> str:
    rows = _ordered_rows(frame, MEDIUM_ORDER)
    body = _rows(
        [
            [
                MEDIUM_LABELS[row.variant_name],
                _fmt(row.agents_evacuated, 1),
                _fmt(row.information_safety_efficiency, 4),
                _fmt(row.harmful_convergence_index, 2),
                _fmt(row.intervention_recipients, 1),
            ]
            for row in rows.itertuples()
        ]
    )
    return rf"""\newcommand{{\llmMediumTable}}{{%
\begin{{table}}[t]
\centering
\small
\resizebox{{\columnwidth}}{{!}}{{%
\begin{{tabular}}{{lrrrr}}
\toprule
Policy & Evacuated & ISE & HCI & Recipients \\
\midrule
{body}
\bottomrule
\end{{tabular}}
}}
\caption{{Medium LLM extension summary over ten seeds. LLM guidance improves
information-safety efficiency mainly by operating under a much smaller
intervention budget, but it does not yet reduce harmful convergence relative
to the strongest conservative baseline.}}
\label{{tab:llm-medium-extension}}
\end{{table}}
}}"""


def _target_table(frame: pd.DataFrame) -> str:
    rows = _ordered_rows(frame, TARGET_ORDER)
    body = _rows(
        [
            [
                TARGET_LABELS[row.variant_name],
                _fmt(row.agents_evacuated, 1),
                _fmt(row.information_safety_efficiency, 4),
                _fmt(row.harmful_convergence_index, 2),
                _fmt(row.intervention_recipients, 1),
            ]
            for row in rows.itertuples()
        ]
    )
    return rf"""\newcommand{{\llmTargetSelectionTable}}{{%
\begin{{table}}[t]
\centering
\small
\resizebox{{\columnwidth}}{{!}}{{%
\begin{{tabular}}{{lrrrr}}
\toprule
Target selector & Evacuated & ISE & HCI & Recipients \\
\midrule
{body}
\bottomrule
\end{{tabular}}
}}
\caption{{LLM target-selection ablation over ten seeds using deterministic
template generation. Message-generation settings are fixed; only recipient
selection changes.}}
\label{{tab:llm-target-selection}}
\end{{table}}
}}"""


def _llm_regime_table(frame: pd.DataFrame) -> str:
    parsed = _parse_llm_regime(frame)
    openai = parsed[parsed["provider"] == "openai"]
    grouped = (
        openai.groupby("hazard_regime", as_index=False)[
            [
                "agents_evacuated",
                "information_safety_efficiency",
                "harmful_convergence_index",
            ]
        ]
        .mean()
        .set_index("hazard_regime")
        .loc[HAZARD_ORDER]
        .reset_index()
    )
    body = _rows(
        [
            [
                HAZARD_LABELS[row.hazard_regime],
                _fmt(row.agents_evacuated, 2),
                _fmt(row.information_safety_efficiency, 4),
                _fmt(row.harmful_convergence_index, 2),
            ]
            for row in grouped.itertuples()
        ]
    )
    return rf"""\newcommand{{\llmRegimeTable}}{{%
\begin{{table}}[t]
\centering
\small
\begin{{tabular}}{{lrrr}}
\toprule
Hazard & Evacuated & ISE & HCI \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\caption{{Focused LLM regime robustness extension, averaged across
low, mixed, and high population-familiarity regimes. The replay-only variants
match the live OpenAI aggregate metrics exactly.}}
\label{{tab:llm-regime-extension}}
\end{{table}}
}}"""


def _regime_comparison_table(det_regime: pd.DataFrame, llm_regime: pd.DataFrame) -> str:
    policy_labels = {
        "static_beacon": "Static beacon",
        "bottleneck_avoidance": "Bottleneck avoidance",
        "entropy_targeted": "Entropy targeted",
        "global_broadcast": "Global broadcast",
    }
    det = det_regime[det_regime["policy"].isin(policy_labels)]
    det = (
        det.groupby("policy", as_index=False)[
            ["information_safety_efficiency", "harmful_convergence_index"]
        ]
        .mean()
        .rename(
            columns={
                "information_safety_efficiency": "det_ise",
                "harmful_convergence_index": "det_hci",
            }
        )
    )
    llm_mean = (
        _parse_llm_regime(llm_regime)
        .query("provider == 'openai'")
        [["information_safety_efficiency", "harmful_convergence_index"]]
        .mean()
    )
    llm_ise = float(llm_mean["information_safety_efficiency"])
    llm_hci = float(llm_mean["harmful_convergence_index"])
    det["_order"] = det["policy"].map({policy: idx for idx, policy in enumerate(policy_labels)})
    det = det.sort_values("_order")
    det["llm_ise_ratio"] = llm_ise / det["det_ise"]
    det["llm_hci_delta"] = llm_hci - det["det_hci"]
    body = _rows(
        [
            [
                policy_labels[row.policy],
                _fmt(row.det_ise, 4),
                _fmt(row.llm_ise_ratio, 2),
                _fmt(row.det_hci, 2),
                _signed(row.llm_hci_delta, 2),
            ]
            for row in det.itertuples()
        ]
    )
    return rf"""\newcommand{{\llmRegimeComparisonTable}}{{%
\begin{{table}}[t]
\centering
\small
\resizebox{{\columnwidth}}{{!}}{{%
\begin{{tabular}}{{lrrrr}}
\toprule
Deterministic policy & Det. ISE & LLM/Det. ISE & Det. HCI & LLM HCI $\Delta$ \\
\midrule
{body}
\bottomrule
\end{{tabular}}
}}
\caption{{Direct comparison between deterministic robustness policies and the
live OpenAI safety-strict LLM extension, averaged across all nine
hazard--familiarity regimes. The deterministic grid uses 20 seeds per cell;
the LLM extension uses five seeds per cell. Positive HCI deltas mean the LLM
extension has higher harmful convergence.}}
\label{{tab:llm-regime-comparison}}
\end{{table}}
}}"""


def _ordered_rows(frame: pd.DataFrame, order: list[str]) -> pd.DataFrame:
    ordered = frame.copy()
    ordered["_order"] = ordered["variant_name"].map({name: index for index, name in enumerate(order)})
    ordered = ordered.dropna(subset=["_order"]).sort_values("_order")
    return ordered.drop(columns=["_order"])


def _parse_llm_regime(frame: pd.DataFrame) -> pd.DataFrame:
    parsed = frame.copy()
    pieces = parsed["variant_name"].str.extract(
        r"hazard_(?P<hazard_regime>[^_]+)__familiarity_(?P<familiarity_regime>[^_]+)__llm_(?P<provider>openai|replay)_safety_strict"
    )
    return pd.concat([parsed, pieces], axis=1).dropna(subset=["hazard_regime", "provider"])


def _rows(rows: Iterable[Iterable[str]]) -> str:
    return "\n".join(" & ".join(row) + r" \\" for row in rows)


def _fmt(value: float, digits: int) -> str:
    return f"{float(value):.{digits}f}"


def _signed(value: float, digits: int) -> str:
    return f"{float(value):+.{digits}f}"


if __name__ == "__main__":
    raise SystemExit(main())
