#!/usr/bin/env python3
"""Emit stats.tex from an exported Chiyoda study bundle.

Usage:
    python3 scripts/gen_stats.py ../out/information_control > stats.tex
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd


def _read_table(root: Path, name: str) -> pd.DataFrame:
    tables = root / "tables"
    parquet = tables / f"{name}.parquet"
    csv = tables / f"{name}.csv"
    if parquet.exists():
        return pd.read_parquet(parquet)
    if csv.exists():
        return pd.read_csv(csv)
    return pd.DataFrame()


def _fmt(value: float, digits: int = 2) -> str:
    return f"{float(value):.{digits}f}"


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: gen_stats.py <study_dir>", file=sys.stderr)
        return 2

    root = Path(argv[1])
    metadata_path = root / "metadata.json"
    metadata = json.loads(metadata_path.read_text(encoding="utf-8")) if metadata_path.exists() else {}
    summary = _read_table(root, "summary")
    interventions = _read_table(root, "interventions")

    variants = summary[summary.get("record_type", "") == "variant_aggregate"] if not summary.empty else pd.DataFrame()
    run_rows = summary[summary.get("record_type", "") == "run"] if not summary.empty else pd.DataFrame()
    best_efficiency = 0.0
    best_policy = "TBD"
    harmful_peak = 0.0
    study_name = str(metadata.get("study_name", "TBD")).replace("_", r"\_")
    if not variants.empty and "information_safety_efficiency" in variants.columns:
        best = variants.sort_values("information_safety_efficiency", ascending=False).iloc[0]
        best_efficiency = float(best["information_safety_efficiency"])
        best_policy = str(best["variant_name"]).replace("_", r"\_")
    if not variants.empty and "harmful_convergence_index" in variants.columns:
        harmful_peak = float(variants["harmful_convergence_index"].max())

    print(r"% Auto-generated by paper/scripts/gen_stats.py -- do not edit.")
    print(rf"\newcommand{{\statStudyName}}{{{study_name}}}")
    print(rf"\newcommand{{\statVariantCount}}{{{int(variants['variant_name'].nunique()) if not variants.empty else 0}}}")
    print(rf"\newcommand{{\statRunCount}}{{{len(run_rows)}}}")
    print(rf"\newcommand{{\statInterventionEvents}}{{{len(interventions)}}}")
    print(rf"\newcommand{{\statBestPolicy}}{{{best_policy}}}")
    print(rf"\newcommand{{\statBestEfficiency}}{{{_fmt(best_efficiency, 3)}}}")
    print(rf"\newcommand{{\statPeakHarmfulConvergence}}{{{_fmt(harmful_peak, 3)}}}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
