//! Deterministic, constraint-preserving scenario generation.

use crate::{ParseError, Scenario, parse, validate};

/// Generate a small multi-level transit scenario from a stable seed.
///
/// The generated source is an input candidate, not benchmark evidence. A
/// benchmark round must still pin the generator version, seed, constraints,
/// and evaluation protocol.
#[must_use]
pub fn source(seed: u64) -> String {
    let mut random = SplitMix64::new(seed);
    let crowd = 80 + random.bounded(121);
    let stair_width_m = f64::from(18 + random.bounded(13)) / 10.0;
    let gate_rate = 12 + random.bounded(19);
    let street_closure_s = 35 + random.bounded(21);
    format!(
        r#"# generated by chiyoda-core {version}; seed {seed}
scenario "generated-interchange-{seed}"
seed {seed}
duration 120s
timestep 100ms
surface platform at (0m, 0m, 6m) size (40m, 16m)
surface concourse at (0m, 0m, 0m) size (40m, 16m)
exit street on concourse at (40m, 8m, 0m) width 3m
exit plaza on concourse at (40m, 2m, 0m) width 3m
stair north_stair from platform at (24m, 8m, 6m) to concourse at (24m, 8m, 0m) width {stair_width_m}m
lift accessible_lift from platform at (5m, 8m, 6m) to concourse at (5m, 8m, 0m) cabin 2m 2m capacity 8 cycle 12s
exit-state planned_street_closure exit street closed time {street_closure_s}s
gate fare_gate on concourse at (32m, 8m, 0m) width 2m capacity {gate_rate}/s to street
agents passengers count {crowd} on platform at (8m, 4m, 6m) to street speed 1.2m/s radius 0.3m height 1.7m alternative plaza release 0s
message false_platform_exit source peer on platform at (16m, 8m, 6m) claim connector north_stair closed truth false time 20s reach 10m trust 0.7
countermeasure staff_correction corrects false_platform_exit source staff on platform at (16m, 8m, 6m) time 35s reach 14m trust 0.9
"#,
        version = crate::LANGUAGE_VERSION,
    )
}

pub fn scenario(seed: u64) -> Result<Scenario, GenerationError> {
    let scenario = parse(&source(seed)).map_err(GenerationError::Parse)?;
    validate(&scenario).map_err(GenerationError::Invalid)?;
    Ok(scenario)
}

#[derive(Debug)]
pub enum GenerationError {
    Parse(ParseError),
    Invalid(Vec<crate::ValidationError>),
}

impl std::fmt::Display for GenerationError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Parse(error) => write!(formatter, "generator emitted invalid source: {error}"),
            Self::Invalid(errors) => {
                write!(formatter, "generator violated constraints: {errors:?}")
            }
        }
    }
}

impl std::error::Error for GenerationError {}

#[derive(Debug, Clone, Copy)]
struct SplitMix64(u64);

impl SplitMix64 {
    const fn new(seed: u64) -> Self {
        Self(seed)
    }

    fn next(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9e37_79b9_7f4a_7c15);
        let mut value = self.0;
        value = (value ^ (value >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        value = (value ^ (value >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
        value ^ (value >> 31)
    }

    fn bounded(&mut self, bound: u32) -> u32 {
        u32::try_from(self.next() % u64::from(bound))
            .expect("a modulo result is strictly below its u32 bound")
    }
}
